### ISSUE TITLE
[Question] Need some clarification on the `remove_outliers` method

### ISSUE THREAD

**Issue by voith** [coinbase/coinbase-nft-floor-price#1]
https://github.com/coinbase/coinbase-nft-floor-price/blob/65389028880576436fd5dd40b6ff77033c5be8ff/cbnftfloorprice.py#L136-L137
Line `136` has `3 * array_mad ` but `137` has `3 + array_mad` (Notice the `*` and `+`)
Shouldn't it be: `ub = array_median + 3 * array_mad`? At least, that's what I think it should be after reading the method docs. 
Please correct me if I'm wrong.

**Comment by irustandi-cb** [comment]
Good catch. Will fix this.
