### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/coinbase-nft-floor-price#3]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/coinbase-nft-floor-price/compare/65389028880576436fd5dd40b6ff77033c5be8ff...aa5ac30290c475d5d1d43173f2e4939d2ff17107) was merged to master by irustandi-cb.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/coinbase-nft-floor-price&ref=e9eccc967fdf8775b51661cf02fa8d1b9c58505c)

**Comment by yifan-cb** [comment]
:+1:

**Comment by yifan-cb** [comment]
:+1:

**Comment by cb-heimdall** [comment]
Review Error for yifan-cb @ 2022-12-20 16:00:28 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Comment by yifan-cb** [comment]
https://github.com/yifan-cb

**Comment by yifan-cb** [comment]
:+1:

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
yifan-cb | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/coinbase-nft-floor-price&ref=e9eccc967fdf8775b51661cf02fa8d1b9c58505c)

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
yifan-cb | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/coinbase-nft-floor-price&ref=e9eccc967fdf8775b51661cf02fa8d1b9c58505c)
